### ISSUE TITLE
 unable to parse out as JSON

### ISSUE THREAD

**Issue by ufo56** [thannaske/telegraf-teamspeak3#4]
Hi

Telegraf console is giving this error.

`2018-08-10T12:25:00Z E! Error in plugin [inputs.exec]: unable to parse out as JSON, invalid character 'e' in literal true (expecting 'r')`

# go version
go version go1.10.3 linux/amd64

**Comment by thannaske** [comment]
This script is providing the statistics with the Influx Line format; not as JSON. Therefore the output is not valid JSON. You need to modify your Telegraf configuration to accept the script output in the Influx format.

**Comment by ufo56** [comment]
thank you. I forget to change that line!
